require 'micro_json/micro_json'
require 'micro_json/json'
require 'micro_json/core_ext/array'
require 'micro_json/core_ext/hash'
require 'micro_json/core_ext/string'
require 'micro_json/core_ext/numeric'
require 'micro_json/core_ext/boolean'
