require 'std/err/abstract_method_error'
require 'std/args_helper'
require 'std/core_ext'
# inflector
require 'std/inflector'
# mixins
require 'std/mixins'
# core
require 'std/set'
require 'std/event'
require 'std/cuboid'
require 'std/aabb'
require 'std/aabbcc'
# internal extension
require 'std/input'
require 'std/input/observer'
require 'std/rect'
require 'std/sprite'
require 'std/vector1'
require 'std/vector2'
require 'std/vector3'
require 'std/vector4'
require 'std/screen'
require 'std/transform'
# addon
require 'std/cache_base'
require 'std/animation'
require 'std/palette_parser'
# timing
require 'std/clock'
# data
require 'std/tree'
# state
require 'std/state_manager'
require 'std/state'
# io
require 'std/io/null'
